#!/usr/bin/env python3
"""Fail if publishable files contain common private-infrastructure artifacts."""

from __future__ import annotations

import hashlib
import re
import sys
from pathlib import Path


ROOT = Path(__file__).resolve().parent.parent
TEXT_SUFFIXES = {
    "",
    ".bat",
    ".command",
    ".cpp",
    ".md",
    ".py",
    ".ps1",
    ".sh",
    ".swift",
    ".txt",
    ".json",
    ".xml",
    ".yml",
    ".yaml",
    ".template",
}
SKIP_DIRS = {".git"}
# Проверенные медиа для README: публикуются только с этим содержимым.
REVIEWED_BINARY_FILES = {
    "docs/media/split-tunneling-demo.gif": "b91e0241a05312a765a6fd7c7f9c5675122d83ed410d646276f46f478dc08f5b",
    "docs/media/split-tunneling-demo.mp4": "d55f1e0e0877ebafc02ec0c3323dd159290c28d8a741be35437f833e26610945",
}
FORBIDDEN_EXACT_FILES = {"config/protected-ips.json"}
FORBIDDEN_PATTERNS = {
    "absolute user path": re.compile(r"(?:/(?:Users|home)/|[A-Za-z]:\\(?:Users)\\)[^/\\\s]+"),
    "VPN share URI": re.compile(r"(?i)\b(?:vless|vmess|trojan|ssr?|hysteria2?|hy2|tuic|wireguard|amneziawg)://"),
    "UUID": re.compile(r"(?i)\b[0-9a-f]{8}-(?:[0-9a-f]{4}-){3}[0-9a-f]{12}\b"),
    "private key": re.compile(r"-----BEGIN [^-]*PRIVATE KEY-----"),
}
FORBIDDEN_FILE_PATTERNS = (
    re.compile(r"(?i)(^|/)(?:\.env|credentials?|secrets?|backups?|logs?|incidents?|runbooks?)(?:/|$)"),
    re.compile(r"(?i)\.(?:key|pem|p12|pfx|mobileconfig|conf)$"),
)


def files() -> list[Path]:
    return [
        path
        for path in ROOT.rglob("*")
        if path.is_file() and not any(part in SKIP_DIRS for part in path.relative_to(ROOT).parts)
    ]


def main() -> int:
    findings: list[str] = []
    for path in files():
        relative = path.relative_to(ROOT).as_posix()
        if "__pycache__" in path.relative_to(ROOT).parts or path.suffix.lower() in {".pyc", ".pyo"}:
            findings.append(f"generated bytecode must not be published: {relative}")
            continue
        if path.name == ".DS_Store":
            findings.append(f"metadata file must not be published: {relative}")
            continue
        if relative in FORBIDDEN_EXACT_FILES:
            findings.append(f"private local config must not be published: {relative}")
            continue
        if any(pattern.search(relative) for pattern in FORBIDDEN_FILE_PATTERNS):
            findings.append(f"forbidden file: {relative}")
            continue
        if relative in REVIEWED_BINARY_FILES:
            if hashlib.sha256(path.read_bytes()).hexdigest() != REVIEWED_BINARY_FILES[relative]:
                findings.append(f"reviewed binary file changed: {relative}")
            continue
        if path.suffix.lower() not in TEXT_SUFFIXES:
            findings.append(f"unreviewed binary file must not be published: {relative}")
            continue
        try:
            text = path.read_text(encoding="utf-8")
        except UnicodeError:
            findings.append(f"non-UTF-8 publishable file: {relative}")
            continue
        for label, pattern in FORBIDDEN_PATTERNS.items():
            if pattern.search(text):
                findings.append(f"{label} in {relative}")
    if findings:
        print("\n".join(sorted(set(findings))), file=sys.stderr)
        return 1
    print("privacy scan: OK")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
